package com.erp.winkaws.mydb.authority;

public enum Permission {

	// FATURALAR
	SATIS_FATURASI, SATIS_IADE_FATURASI, ALIS_FATURASI, ALIS_IADE_FATURASI,

	// SIPARISLER
	ALINAN_SIPARIS, VERILEN_SIPARIS,

	// FIYAT TEKLIFLERI
	ALINAN_FIYAT_TEKLIFI, VERILEN_FIYAT_TEKLIFI,

	// STOK ISLEMLERI
	DEPO_TRANSFER, SAYIM, STOK_GIRIS_BELGESI, STOK_CIKIS_BELGESI,

	// KART ISLEMLERI
	STOK_KARTI_ACAR, CARI_KARTI_ACAR,

	// RAPORLAR
	STOK_RAPORLARI, CARI_RAPORLARI, FATURA_RAPORLARI, MAGAZA_RAPORLARI, OZEL_RAPORLAR,

	// CARI ISLEMLERI
	CARI_GIRIS, CARI_CIKIS,

	// YETKI / KURAL
	KENDI_SUBE_CARILERINI_GORSUN, BASKA_SUBEDEN_SATIS_YAPSIN, RENK_BEDENSIZ, ISKONTO_YAPAMAZ, SATIR_ISKONTOSU_YAPAMAZ,
	FATURA_TARIHI_DEGISTIRIR, KASA_DEGISTIRIR, PESIN_VADELI

}
