spring.application.name=winkaws
server.port=58001

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:14b
spring.ai.ollama.chat.options.temperature=0
spring.ai.ollama.chat.options.top-p=0.9
spring.ai.ollama.chat.options.num-predict=2048

# ---------------- Primary DB (CodeDB_1) ----------------
spring.datasource.primary.jdbc-url=jdbc:sqlserver://127.0.0.1:1433;databaseName=CodeDB_1;encrypt=true;trustServerCertificate=true;
spring.datasource.primary.username=sa
spring.datasource.primary.password=Qaz123!a
spring.datasource.primary.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.primary.hibernate.ddl-auto=none
spring.jpa.primary.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.primary.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.primary.show-sql=true

# ---------------- Secondary DB (vtmaster) ----------------
spring.datasource.secondary.jdbc-url=jdbc:sqlserver://127.0.0.1:1433;databaseName=vtmaster;encrypt=true;trustServerCertificate=true;
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=Qaz123!a
spring.datasource.secondary.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.secondary.hibernate.ddl-auto=none
spring.jpa.secondary.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.secondary.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.secondary.show-sql=true

# ---------------- Third DB (mydb) ----------------
spring.datasource.third.jdbc-url=jdbc:sqlserver://127.0.0.1:1433;databaseName=meganet;encrypt=true;trustServerCertificate=true;
spring.datasource.third.username=sa
spring.datasource.third.password=Qaz123!a
spring.datasource.third.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.third.hibernate.ddl-auto=update
spring.jpa.third.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.third.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.third.show-sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ---------------- Genel Ayarlar ----------------
spring.profiles.active=production
logging.level.org.springframework.security=DEBUG
spring.jpa.open-in-view=false
# select authorization : jwt , basic, opaque
winka.token-type=opaque
spring.config.activate.on-profile=production

winka.barcode-number=22544

